schema: "paperclip/v1"
agents:
  billy-pham:
    role: "general"
    adapter:
      config:
        dangerouslySkipPermissions: true
      type: "claude_local"
    runtime:
      heartbeat:
        intervalSec: 300
        maxConcurrentRuns: 1
  ceo:
    role: "ceo"
    adapter:
      config:
        dangerouslySkipPermissions: true
      type: "claude_local"
    runtime:
      heartbeat:
        intervalSec: 600
        maxConcurrentRuns: 1
    permissions:
      canCreateAgents: true
  hannah-soto:
    role: "general"
    adapter:
      config:
        dangerouslySkipPermissions: true
      type: "claude_local"
    runtime:
      heartbeat:
        intervalSec: 300
        maxConcurrentRuns: 1
  hiep-nguyen:
    role: "general"
    adapter:
      config:
        dangerouslySkipPermissions: true
      type: "claude_local"
    runtime:
      heartbeat:
        intervalSec: 300
        maxConcurrentRuns: 1
  paolo-la-rosa:
    role: "general"
    adapter:
      config:
        dangerouslySkipPermissions: true
      type: "claude_local"
    runtime:
      heartbeat:
        intervalSec: 300
        maxConcurrentRuns: 1
sidebar:
  agents:
    - "ceo"
    - "billy-pham"
    - "hannah-soto"
    - "hiep-nguyen"
    - "paolo-la-rosa"
